---
- name: Manage Windows
  hosts: win
  become: false
  tasks:
  - name: Pause for 1 minutes to build app cache
    pause:
      minutes: 1
  - name: Run multi-lined shell commands
    win_shell: |
      $value = Test-Path -Path C:\temporal
      if ($value) {
          Remove-Item -Path C:\temporal -Force
      }
      New-Item -Path C:\temporal -ItemType Directory
  - name: Copy file    
    win_copy:
      src: ConfigureRemotingForAnsible.ps1
      dest: C:\temporal\
