---
- name: Manage Windows
  hosts: win
  become: false
  tasks:
  - name: Wait for port 5986 (winrm) to become open on the host, don't start checking for 10 seconds
    wait_for:
      port: 5986
      delay: 10
    ignore_errors: yes  
  - name: Run multi-lined shell commands
    win_shell: |
      $value = Test-Path -Path C:\temporal
      if ($value) {
          Remove-Item -Path C:\temporal -Force
      }
      New-Item -Path C:\temporal -ItemType Directory
  - name: Copy file    
    win_copy:
      src: ConfigureRemotingForAnsible.ps1
      dest: C:\temporal\
